// Package loadpkg discovers source directives and handwritten source metadata
// for package-wide monoslices generation.
package loadpkg

import (
	"context"
	"fmt"
	"go/ast"
	"go/build"
	"go/build/constraint"
	"go/parser"
	"go/token"
	"go/version"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/zolstein/monoslices/internal/config"
)

const directivePrefix = "//monoslices:generate"

// GeneratedOwnershipComment marks files owned by monoslices. Source discovery
// excludes these files, and regeneration removes stale ones after writing the
// new output.
const GeneratedOwnershipComment = "Code generated by monoslices. DO NOT EDIT."

// DirectiveLocation identifies a source directive for diagnostics and source
// ordering. Path is the cleaned absolute path; Filename is its package-local
// basename.
type DirectiveLocation struct {
	Filename string
	Path     string
	Line     int
	Column   int
	Offset   int
}

// Errorf formats an error at a package-local source position.
func (d DirectiveLocation) Errorf(format string, args ...any) error {
	filename := d.Filename
	if filename == "" {
		filename = filepath.Base(d.Path)
	}
	return fmt.Errorf("%s:%d:%d: monoslices: %s", filename, d.Line, d.Column, fmt.Sprintf(format, args...))
}

// SourceConstraint records the source provenance that makes a file build
// constrained. The generator retains this metadata for source diagnostics and
// rejects constrained directives instead of solving arbitrary compatibility.
type SourceConstraint struct {
	Constrained       bool
	GoBuildExpression string
	RequiresCgo       bool
}

// SourceFuncDecl records a package-level function declaration from source.
// Decl points into the AST retained by its SourceFile.
type SourceFuncDecl struct {
	Name        string
	Filename    string
	Path        string
	Line        int
	Column      int
	Offset      int
	Decl        *ast.FuncDecl
	Constrained bool
}

// SourceFile is one parsed handwritten Go source file. Source discovery parses
// every inventoried file with the go/parser linked into this executable before
// considering build constraints, so inactive files have the same parseability
// requirement. One token.FileSet keeps offsets and positions comparable across
// the complete source inventory.
type SourceFile struct {
	Filename     string
	Path         string
	PackageName  string
	Test         bool
	ExternalTest bool
	Source       []byte
	AST          *ast.File
	Constraint   SourceConstraint
	Declarations []SourceDeclaration
	Imports      []SourceImport
	Functions    []SourceFuncDecl
}

// SourceDeclaration is a package-level declaration found from a parsed
// source AST. This includes names from inactive build-constrained files and
// same-package test files so an unconditional generated file can reserve the
// complete source namespace.
type SourceDeclaration struct {
	Name        string
	PackageName string
	Filename    string
	Path        string
	Line        int
	Column      int
	Offset      int
	Constrained bool
}

// SourceImport is an import binding known from source syntax. Explicit aliases
// and the fixed C pseudo-package binding have known names; default imports have
// no known Name. Dot imports retain their direct source provenance and are
// rejected when directives are present.
type SourceImport struct {
	// Name is a syntactically known source binding. It is empty for default
	// imports; explicit aliases and the fixed C pseudo-package binding are
	// settled during source discovery.
	Name          string
	ImportPath    string
	ExplicitAlias bool
	PackageName   string
	Filename      string
	Path          string
	Line          int
	Column        int
	Offset        int
	Constrained   bool
	Dot           bool
	// Test identifies imports collected from _test.go files. External test
	// package imports are excluded from generated-package namespace planning,
	// while same-package test imports participate.
	Test bool
}

// Directive is one accepted package-wide source directive.
type Directive struct {
	Config   config.DirectiveConfig
	Filename string
	Path     string
	Line     int
	Column   int
	Offset   int
}

func (d Directive) location() DirectiveLocation {
	return DirectiveLocation{
		Filename: d.Filename,
		Path:     d.Path,
		Line:     d.Line,
		Column:   d.Column,
		Offset:   d.Offset,
	}
}

// Errorf formats an error at this directive's source position.
func (d Directive) Errorf(format string, args ...any) error {
	return d.location().Errorf(format, args...)
}

// Package is source metadata used by the aggregate operation model.
// SourceFiles retain each directive's file and specialization function
// declarations so source types can be copied without reconstructing
// declarations from another file or build context. Paths are retained for
// loading and output validation only; they are not intended to be copied into
// generated source.
type Package struct {
	Dir  string
	Name string
	// SourceFset is the single FileSet used for all SourceFiles.
	SourceFset *token.FileSet
	OutputPath string
	Directives []Directive
	OwnedFiles []string

	// SourceFiles is the authoritative parsed handwritten source inventory.
	// It includes external test files for source diagnostics; consumers select
	// production and same-package-test files with ExternalTest.
	SourceFiles []SourceFile
}

// LoadPackage discovers package-wide source metadata without type-checking the
// source package. Package identity comes from parsed handwritten production
// source, so owned generated output cannot influence package selection.
func LoadPackage(ctx context.Context, cwd string, cfg config.CLIConfig) (*Package, error) {
	packageDir, err := resolveWorkingDirectory(cwd)
	if err != nil {
		return nil, err
	}
	outputPath, err := resolveOutputPath(packageDir, packageDir, cfg)
	if err != nil {
		return nil, err
	}
	source, err := discoverSourceMetadata(packageDir, outputPath)
	if err != nil {
		return nil, err
	}
	packageName := source.productionPackage
	if packageName == "" {
		return nil, diagnostic("package in %s has no production source package name", packageDir)
	}

	return &Package{
		Dir:         packageDir,
		Name:        packageName,
		SourceFset:  source.fset,
		OutputPath:  outputPath,
		Directives:  source.directives,
		OwnedFiles:  source.ownedFiles,
		SourceFiles: source.files,
	}, nil
}

func resolveWorkingDirectory(cwd string) (string, error) {
	root, err := filepath.Abs(cwd)
	if err != nil {
		return "", diagnostic("cannot resolve working directory %q: %v", cwd, err)
	}
	root = filepath.Clean(root)
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return "", diagnostic("cannot resolve working directory %q: %v", cwd, err)
	}
	return root, nil
}

// resolveOutputPath resolves package-wide output relative to cwd. The
// directory must resolve to the package directory, so output cannot escape
// the package through traversal or a parent-directory symlink.
func resolveOutputPath(packageDir, cwd string, cfg config.CLIConfig) (string, error) {
	name := cfg.Out
	if cfg.OutSet && name == "" {
		return "", diagnostic("-out=%q must not be empty", name)
	}
	if !cfg.OutSet && name == "" {
		name = config.DefaultOutputFilename
	}
	return resolveOutputPathName(packageDir, cwd, name)
}

func resolveOutputPathName(packageDir, cwd, name string) (string, error) {
	path := name
	if !filepath.IsAbs(path) {
		path = filepath.Join(cwd, path)
	}
	path, err := filepath.Abs(path)
	if err != nil {
		return "", diagnostic("cannot resolve output path %q: %v", name, err)
	}
	path = filepath.Clean(path)
	if !strings.HasSuffix(filepath.Base(path), ".go") {
		return "", diagnostic("output path %q must end in .go", name)
	}
	parent := filepath.Dir(path)
	resolvedParent, err := filepath.EvalSymlinks(parent)
	if err != nil {
		return "", diagnostic("cannot resolve output directory %q: %v", parent, err)
	}
	resolvedParent, err = filepath.Abs(resolvedParent)
	if err != nil {
		return "", diagnostic("cannot resolve output directory %q: %v", parent, err)
	}
	packageDir, err = filepath.Abs(packageDir)
	if err != nil {
		return "", diagnostic("cannot resolve package directory: %v", err)
	}
	if filepath.Clean(resolvedParent) != filepath.Clean(packageDir) {
		return "", diagnostic("output path %q is outside package directory %q", name, packageDir)
	}
	if err := validateOutputBasename(filepath.Base(path)); err != nil {
		return "", err
	}
	return filepath.Join(resolvedParent, filepath.Base(path)), nil
}

func validateOutputBasename(name string) error {
	if err := config.ValidateOutputBasename(name); err != nil {
		return err
	}
	constrained, err := filenameIsPlatformConstrained(name)
	if err != nil {
		return diagnostic("cannot classify output filename %q: %v", name, err)
	}
	if constrained {
		return diagnostic("output filename %q must be an ordinary production Go source filename: filename implies a GOOS/GOARCH constraint", name)
	}
	return nil
}

// filenameIsPlatformConstrained asks the go/build implementation linked into
// this executable whether the filename has an implicit GOOS/GOARCH constraint.
// Synthetic source keeps explicit build constraints in the actual file out of
// this classification.
func filenameIsPlatformConstrained(name string) (bool, error) {
	matches := func(goos, goarch string) (bool, error) {
		ctxt := build.Default
		ctxt.GOOS = goos
		ctxt.GOARCH = goarch
		ctxt.OpenFile = func(string) (io.ReadCloser, error) {
			return io.NopCloser(strings.NewReader("package p\n")), nil
		}
		return ctxt.MatchFile("", name)
	}

	first, err := matches("linux", "amd64")
	if err != nil {
		return false, err
	}
	second, err := matches("windows", "arm64")
	if err != nil {
		return false, err
	}
	return !first || !second, nil
}

type sourceConstraintInfo struct {
	goBuildExpression string
	cgo               bool
	constrained       bool
}

type sourceFile struct {
	SourceFile
	constraint sourceConstraintInfo
}

type sourceMetadata struct {
	directives        []Directive
	files             []SourceFile
	ownedFiles        []string
	fset              *token.FileSet
	productionPackage string
}

func discoverSourceMetadata(packageDir, outputPath string) (sourceMetadata, error) {
	entries, err := os.ReadDir(packageDir)
	if err != nil {
		return sourceMetadata{}, diagnostic("cannot read package directory %q: %v", packageDir, err)
	}
	files := make([]sourceFile, 0, len(entries))
	outputPath = cleanAbsolute(outputPath)
	sourceSet := token.NewFileSet()
	ownedFiles := make([]string, 0)
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") {
			continue
		}
		path := cleanAbsolute(filepath.Join(packageDir, name))
		data, err := os.ReadFile(path)
		if err != nil {
			return sourceMetadata{}, diagnostic("cannot read source file %q: %v", name, err)
		}
		if hasGeneratedOwnershipComment(data) {
			ownedFiles = append(ownedFiles, path)
			continue
		}
		if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") || path == outputPath {
			continue
		}
		file, err := parser.ParseFile(sourceSet, path, data, parser.ParseComments|parser.SkipObjectResolution)
		if err != nil {
			return sourceMetadata{}, sourceParseError(name, data, err, embeddedParserLanguageVersion())
		}
		constraintInfo, err := sourceConstraintForParsedFile(name, data, file)
		if err != nil {
			return sourceMetadata{}, diagnostic("cannot classify source filename %q: %v", name, err)
		}
		source := sourceFile{
			SourceFile: SourceFile{
				Filename:   name,
				Path:       path,
				Test:       strings.HasSuffix(name, "_test.go"),
				Source:     data,
				AST:        file,
				Constraint: publicSourceConstraint(constraintInfo),
			},
			constraint: constraintInfo,
		}
		source.PackageName = file.Name.Name
		source.Declarations = collectSourceDeclarations(source, sourceSet, file)
		source.Imports = collectSourceImports(source, sourceSet, file)
		source.Functions = collectSourceFunctions(source, sourceSet, file)
		files = append(files, source)
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Filename < files[j].Filename })

	sort.Strings(ownedFiles)
	result := sourceMetadata{fset: sourceSet, ownedFiles: ownedFiles}
	// Establish production identity before classifying test files. Every
	// non-test source variant participates, regardless of its constraint.
	for _, source := range files {
		if source.Test {
			continue
		}
		if result.productionPackage == "" {
			result.productionPackage = source.PackageName
			continue
		}
		if source.PackageName != result.productionPackage {
			position := sourceSet.Position(source.AST.Name.Pos())
			location := DirectiveLocation{Filename: source.Filename, Path: source.Path, Line: position.Line, Column: position.Column, Offset: position.Offset}
			return sourceMetadata{}, location.Errorf("conflicting production package names %q and %q", result.productionPackage, source.PackageName)
		}
	}
	if result.productionPackage == "" {
		return sourceMetadata{}, diagnostic("package in %s has no production source package name", packageDir)
	}

	for index := range files {
		source := &files[index]
		source.ExternalTest = source.Test && source.PackageName != result.productionPackage
		for _, found := range directivesFromComments(sourceSet, *source) {
			location := DirectiveLocation{Filename: source.Filename, Path: source.Path, Line: found.line, Column: found.column, Offset: found.offset}
			if source.Test {
				return sourceMetadata{}, location.Errorf("directives in test files are not supported")
			}
			if source.constraint.constrained {
				return sourceMetadata{}, location.Errorf("directives in build-constrained files are not supported")
			}
			parsed, err := config.ParseDirective(found.suffix)
			if err != nil {
				return sourceMetadata{}, location.Errorf("%s", trimDiagnosticPrefix(err))
			}
			result.directives = append(result.directives, Directive{Config: parsed, Filename: source.Filename, Path: source.Path, Line: found.line, Column: found.column, Offset: found.offset})
		}
		result.files = append(result.files, source.SourceFile)
	}
	sort.SliceStable(result.directives, func(i, j int) bool {
		if result.directives[i].Filename != result.directives[j].Filename {
			return result.directives[i].Filename < result.directives[j].Filename
		}
		return result.directives[i].Offset < result.directives[j].Offset
	})
	return result, nil
}

func hasGeneratedOwnershipComment(source []byte) bool {
	for _, line := range strings.Split(string(source), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "//") && strings.TrimSpace(strings.TrimPrefix(line, "//")) == GeneratedOwnershipComment {
			return true
		}
	}
	return false
}

func collectSourceDeclarations(source sourceFile, fileSet *token.FileSet, file *ast.File) []SourceDeclaration {
	declarations := make([]SourceDeclaration, 0)
	add := func(identifier *ast.Ident) {
		if identifier == nil || identifier.Name == "_" {
			return
		}
		position := fileSet.Position(identifier.Pos())
		declarations = append(declarations, SourceDeclaration{
			Name:        identifier.Name,
			PackageName: file.Name.Name,
			Filename:    source.Filename,
			Path:        source.Path,
			Line:        position.Line,
			Column:      position.Column,
			Offset:      position.Offset,
			Constrained: source.constraint.constrained,
		})
	}
	for _, declaration := range file.Decls {
		switch declaration := declaration.(type) {
		case *ast.FuncDecl:
			if declaration.Recv == nil {
				add(declaration.Name)
			}
		case *ast.GenDecl:
			switch declaration.Tok {
			case token.CONST, token.VAR:
				for _, specification := range declaration.Specs {
					value, ok := specification.(*ast.ValueSpec)
					if !ok {
						continue
					}
					for _, name := range value.Names {
						add(name)
					}
				}
			case token.TYPE:
				for _, specification := range declaration.Specs {
					typeSpec, ok := specification.(*ast.TypeSpec)
					if ok {
						add(typeSpec.Name)
					}
				}
			}
		}
	}
	return declarations
}

// collectSourceImports records only import names that can be determined from
// source syntax. This is deliberately useful for inactive and test files: an
// explicit alias is its own binding, while a default import remains unresolved.
func collectSourceImports(source sourceFile, fileSet *token.FileSet, file *ast.File) []SourceImport {
	imports := make([]SourceImport, 0, len(file.Imports))
	for _, specification := range file.Imports {
		path, err := strconv.Unquote(specification.Path.Value)
		if err != nil {
			continue
		}
		name := ""
		dot := false
		var positionNode ast.Node = specification.Path
		if specification.Name != nil {
			name = specification.Name.Name
			positionNode = specification.Name
			dot = name == "."
		}
		if name == "_" {
			continue
		}
		if path == "C" && name == "" {
			// The cgo pseudo-package has a fixed source binding.
			name = "C"
		}
		// Keep default imports in the source model even though their local
		// package names are not available from the import declaration.
		position := fileSet.Position(positionNode.Pos())
		imports = append(imports, SourceImport{
			Name:          name,
			ImportPath:    path,
			ExplicitAlias: specification.Name != nil,
			PackageName:   file.Name.Name,
			Filename:      source.Filename,
			Path:          source.Path,
			Line:          position.Line,
			Column:        position.Column,
			Offset:        position.Offset,
			Constrained:   source.constraint.constrained,
			Dot:           dot,
			Test:          source.Test,
		})
	}
	return imports
}

func collectSourceFunctions(source sourceFile, fileSet *token.FileSet, file *ast.File) []SourceFuncDecl {
	functions := make([]SourceFuncDecl, 0)
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Recv != nil || function.Name == nil {
			continue
		}
		position := fileSet.Position(function.Name.Pos())
		functions = append(functions, SourceFuncDecl{
			Name:        function.Name.Name,
			Filename:    source.Filename,
			Path:        source.Path,
			Line:        position.Line,
			Column:      position.Column,
			Offset:      position.Offset,
			Decl:        function,
			Constrained: source.constraint.constrained,
		})
	}
	return functions
}

type foundDirective struct {
	suffix string
	line   int
	column int
	offset int
}

// directivesFromComments derives directives from the already parsed AST. It
// intentionally does not scan source bytes a second time: comments, package
// clauses, imports, declarations, and functions all come from one parse.
func directivesFromComments(fileSet *token.FileSet, source sourceFile) []foundDirective {
	result := make([]foundDirective, 0)
	if source.AST == nil {
		return result
	}
	for _, group := range source.AST.Comments {
		for _, comment := range group.List {
			text := comment.Text
			if !strings.HasPrefix(text, directivePrefix) || !strings.HasPrefix(text, "//") {
				continue
			}
			suffix := text[len(directivePrefix):]
			if suffix != "" {
				runeValue, _ := utf8.DecodeRuneInString(suffix)
				if !unicode.IsSpace(runeValue) {
					continue
				}
			}
			position := fileSet.Position(comment.Pos())
			result = append(result, foundDirective{suffix: suffix, line: position.Line, column: position.Column, offset: position.Offset})
		}
	}
	return result
}

func hasExplicitBuildConstraint(data []byte) bool {
	_, _, found, _ := parseHeaderConstraints(data)
	return found
}

func requiredSourceGoVersion(data []byte) string {
	goBuildLine, plusBuildLines, _, multipleGoBuild := parseHeaderConstraints(data)
	if multipleGoBuild {
		return ""
	}
	if goBuildLine != "" {
		expression, err := constraint.Parse(goBuildLine)
		if err != nil {
			return ""
		}
		return constraint.GoVersion(expression)
	}
	if len(plusBuildLines) == 0 {
		return ""
	}

	var combined constraint.Expr
	for _, line := range plusBuildLines {
		expression, err := constraint.Parse(line)
		if err != nil {
			return ""
		}
		if combined == nil {
			combined = expression
		} else {
			combined = &constraint.AndExpr{X: combined, Y: expression}
		}
	}
	return constraint.GoVersion(combined)
}

func embeddedParserLanguageVersion() string {
	return version.Lang(runtime.Version())
}

// sourceParseError preserves the embedded parser's failure and adds release
// context when the file constraints require a newer Go version.
func sourceParseError(filename string, data []byte, parseErr error, parserVersion string) error {
	message := fmt.Sprintf("cannot parse source file %q: %v", filename, parseErr)
	requiredVersion := requiredSourceGoVersion(data)
	if requiredVersion != "" && version.IsValid(parserVersion) && version.Compare(requiredVersion, parserVersion) > 0 {
		message += fmt.Sprintf("; file build constraints require Go %s, while this monoslices executable was built with Go %s", strings.TrimPrefix(requiredVersion, "go"), strings.TrimPrefix(parserVersion, "go"))
	}
	return diagnostic("%s", message)
}

// parseHeaderConstraints extracts the build constraints recognized in a Go
// source header. It deliberately mirrors hasExplicitBuildConstraint's header
// boundary rules instead of searching comments indiscriminately.
func parseHeaderConstraints(data []byte) (goBuildLine string, plusBuildLines []string, found, multipleGoBuild bool) {
	content := strings.TrimPrefix(string(data), "\uFEFF")
	end := 0
	offset := 0
	ended := false
	inSlashStar := false
	goBuildCount := 0

scanHeader:
	for offset < len(content) {
		line := content[offset:]
		if newline := strings.IndexByte(line, '\n'); newline >= 0 {
			line, offset = line[:newline], offset+newline+1
		} else {
			offset = len(content)
		}
		line = strings.TrimSpace(line)
		if line == "" && !ended {
			end = offset
			continue
		}
		if !strings.HasPrefix(line, "//") {
			ended = true
		}
		if !ended && !inSlashStar && constraint.IsGoBuild(line) {
			found = true
			goBuildCount++
			if goBuildCount == 1 {
				goBuildLine = line
			}
		}

		for len(line) > 0 {
			if inSlashStar {
				close := strings.Index(line, "*/")
				if close < 0 {
					continue scanHeader
				}
				inSlashStar = false
				line = strings.TrimSpace(line[close+len("*/"):])
				continue
			}
			if strings.HasPrefix(line, "//") {
				continue scanHeader
			}
			if strings.HasPrefix(line, "/*") {
				inSlashStar = true
				line = strings.TrimSpace(line[len("/*"):])
				continue
			}
			break scanHeader
		}
	}

	// Unlike //go:build, a legacy +build line is effective only when it is
	// separated from the package clause by a blank line.
	for _, rawLine := range strings.Split(content[:end], "\n") {
		line := strings.TrimSpace(rawLine)
		if constraint.IsPlusBuild(line) {
			found = true
			plusBuildLines = append(plusBuildLines, line)
		}
	}
	return goBuildLine, plusBuildLines, found, goBuildCount > 1
}

// sourceConstraintForParsedFile derives cgo provenance from the already parsed
// AST used by source discovery.
func sourceConstraintForParsedFile(name string, data []byte, file *ast.File) (sourceConstraintInfo, error) {
	hasCgo := false
	if file != nil {
		for _, specification := range file.Imports {
			path, err := strconv.Unquote(specification.Path.Value)
			if err == nil && path == "C" {
				hasCgo = true
				break
			}
		}
	}
	return sourceConstraintForData(name, data, hasCgo)
}

func sourceConstraintForData(name string, data []byte, hasCgo bool) (sourceConstraintInfo, error) {
	goBuildLine, plusBuildLines, found, _ := parseHeaderConstraints(data)
	result := sourceConstraintInfo{constrained: found}
	// Keep the source expression as provenance. It is intentionally not parsed
	// or compared with another file's expression.
	if goBuildLine != "" {
		result.goBuildExpression = strings.TrimSpace(strings.TrimPrefix(goBuildLine, "//go:build"))
	} else if len(plusBuildLines) != 0 {
		expressions := make([]string, 0, len(plusBuildLines))
		for _, line := range plusBuildLines {
			line = strings.TrimSpace(strings.TrimPrefix(line, "//"))
			expressions = append(expressions, strings.TrimSpace(strings.TrimPrefix(line, "+build")))
		}
		result.goBuildExpression = strings.Join(expressions, "\n")
	}
	filenameConstrained, err := filenameIsPlatformConstrained(name)
	if err != nil {
		return sourceConstraintInfo{}, err
	}
	if filenameConstrained {
		result.constrained = true
	}
	if hasCgo {
		result.cgo = true
		result.constrained = true
	}
	return result, nil
}

func publicSourceConstraint(info sourceConstraintInfo) SourceConstraint {
	return SourceConstraint{
		Constrained:       info.constrained,
		GoBuildExpression: info.goBuildExpression,
		RequiresCgo:       info.cgo,
	}
}

func trimDiagnosticPrefix(err error) string {
	message := err.Error()
	return strings.TrimPrefix(message, "monoslices: ")
}

func cleanAbsolute(path string) string {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return filepath.Clean(path)
	}
	return filepath.Clean(absolute)
}

func diagnostic(format string, args ...any) error {
	return fmt.Errorf("monoslices: "+format, args...)
}
