package loadpkg

import (
	"context"
	"errors"
	"go/ast"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/zolstein/monoslices/internal/config"
)

func TestLoadPackageDiscoversDirectivesInDeterministicOrder(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"z_records.go": `package sample
// monoslices:generate name=Ignored cmp=compare
//monoslices:generate name=Zulu cmp=compare
`,
		"a_records.go": `package sample

type A int
func compare(a, b A) int { return int(a-b) }
//monoslices:generate name=Alpha cmp=compare
//monoslices:generateX name=Ignored cmp=compare
`,
		"monoslices_gen.go": `// Code generated by monoslices. DO NOT EDIT.
package stale
func stale() {}
`,
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	if got, want := loaded.OutputPath, filepath.Join(dir, config.DefaultOutputFilename); got != want {
		t.Fatalf("OutputPath = %q, want %q", got, want)
	}
	if len(loaded.Directives) != 2 || loaded.Directives[0].Config.Name != "Alpha" || loaded.Directives[1].Config.Name != "Zulu" {
		t.Fatalf("directives = %#v", loaded.Directives)
	}
	if len(loaded.OwnedFiles) != 1 || filepath.Base(loaded.OwnedFiles[0]) != "monoslices_gen.go" {
		t.Fatalf("owned files = %#v, want monoslices_gen.go", loaded.OwnedFiles)
	}
	for _, file := range loaded.SourceFiles {
		if file.Filename == "monoslices_gen.go" {
			t.Fatal("owned output was included in handwritten source inventory")
		}
	}
}

func TestLoadPackageAllowsSyntacticallyValidTypeErrors(t *testing.T) {
	tests := []struct {
		name          string
		extraSource   string
		function      string
		parameterType string
		operations    string
	}{
		{
			name:          "undefined identifier in ordinary body",
			extraSource:   "func broken() { missing() }",
			function:      "broken",
			parameterType: "Item",
			operations:    "compare",
		},
		{
			name:          "invalid specialization body",
			extraSource:   "func compare(a, b Item) int { return unresolved(a, b) }",
			function:      "compare",
			parameterType: "Item",
			operations:    "compare",
		},
		{
			name:          "missing generated public operation",
			extraSource:   "func useItems(items []Item) { ItemsSort(items) }",
			function:      "useItems",
			parameterType: "Item",
			operations:    "sort",
		},
		{
			name:          "unresolved local specialization type",
			extraSource:   "func compare(a, b Missing) int { return 0 }",
			function:      "compare",
			parameterType: "Missing",
			operations:    "compare",
		},
		{
			name:          "invalid declaration",
			extraSource:   "var invalid int = \"not an int\"",
			function:      "compare",
			parameterType: "Item",
			operations:    "compare",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			source := "package sample\n\ntype Item int\n" + test.extraSource + "\n"
			if !strings.Contains(test.extraSource, "func compare") {
				source += "func compare(a, b Item) int { return 0 }\n"
			}
			source += "//monoslices:generate name=Items cmp=compare ops=" + test.operations + "\n"
			dir := packageDir(t, map[string]string{"records.go": source})
			loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
			if err != nil {
				t.Fatalf("LoadPackage() error = %v", err)
			}
			if len(loaded.Directives) != 1 || loaded.Directives[0].Config.Name != "Items" {
				t.Fatalf("directives = %#v, want Items directive", loaded.Directives)
			}
			var target, compare *SourceFuncDecl
			for fileIndex := range loaded.SourceFiles {
				file := &loaded.SourceFiles[fileIndex]
				if file.Filename != "records.go" {
					continue
				}
				for functionIndex := range file.Functions {
					function := &file.Functions[functionIndex]
					if function.Name == test.function {
						target = function
					}
					if function.Name == "compare" {
						compare = function
					}
				}
			}
			if target == nil || target.Decl == nil {
				t.Fatalf("source function %q was not discovered", test.function)
			}
			if compare == nil || compare.Decl == nil {
				t.Fatal("specialization source function compare was not discovered")
			}
			params := compare.Decl.Type.Params
			if params == nil || len(params.List) != 1 || len(params.List[0].Names) != 2 {
				t.Fatalf("source parameters = %#v, want grouped pair", params)
			}
			typeName, ok := params.List[0].Type.(*ast.Ident)
			if !ok || typeName.Name != test.parameterType {
				t.Fatalf("source parameter type = %#v, want %s", params.List[0].Type, test.parameterType)
			}
		})
	}
}

func TestLoadPackageRejectsParseErrors(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": "package sample\nfunc broken( {\n",
	})
	_, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err == nil || !strings.Contains(err.Error(), "records.go") || !strings.Contains(err.Error(), "cannot parse source file") {
		t.Fatalf("LoadPackage() error = %v, want parser diagnostic", err)
	}
}

func TestLoadPackageExposesUnifiedSourceInventory(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": `package sample

type Item int
func compare(left, right Item) int { return int(left - right) }
//monoslices:generate name=Items cmp=compare ops=sort
`,
		"records_windows.go": `//go:build windows

package sample

const InactiveVariant = 1
func variantCmp(a, b Item) int { return int(a - b) }
`,
		"records_test.go": `package sample

const SamePackageTest = 1
`,
		"external_test.go": `package sample_test

const ExternalTest = 1
`,
		"monoslices_gen.go": "package stale\nconst StaleOutput = 1\n",
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	if loaded.Name != "sample" {
		t.Fatalf("package name = %q, want sample", loaded.Name)
	}
	if loaded.SourceFset == nil || len(loaded.SourceFiles) != 4 {
		t.Fatalf("source inventory = fset %v, %d files; want one fset and four files", loaded.SourceFset != nil, len(loaded.SourceFiles))
	}
	var foundInactive, foundVariantFunction, foundSame, foundExternal bool
	for _, file := range loaded.SourceFiles {
		switch file.Filename {
		case "records_windows.go":
			if !file.Constraint.Constrained || file.Constraint.GoBuildExpression != "windows" {
				t.Fatalf("windows source constraint = %#v", file.Constraint)
			}
			for _, declaration := range file.Declarations {
				if declaration.Name == "InactiveVariant" {
					foundInactive = true
				}
			}
			for _, function := range file.Functions {
				if function.Name == "variantCmp" {
					if !function.Constrained {
						t.Fatalf("constrained source function = %#v", function)
					}
					foundVariantFunction = true
				}
			}
		case "records_test.go":
			if !file.Test || file.ExternalTest {
				t.Fatalf("same-package test classification = test %v external %v", file.Test, file.ExternalTest)
			}
			for _, declaration := range file.Declarations {
				if declaration.Name == "SamePackageTest" {
					foundSame = true
				}
			}
		case "external_test.go":
			if !file.Test || !file.ExternalTest {
				t.Fatalf("external test classification = test %v external %v", file.Test, file.ExternalTest)
			}
			for _, declaration := range file.Declarations {
				if declaration.Name == "ExternalTest" {
					foundExternal = true
				}
			}
		}
	}
	for _, declaration := range includedSourceDeclarations(loaded) {
		if declaration.Name == "InactiveVariant" {
			foundInactive = true
		}
	}
	if !foundInactive || !foundVariantFunction || !foundSame || !foundExternal {
		t.Fatalf("source inventory: inactive=%v variant function=%v same=%v external=%v", foundInactive, foundVariantFunction, foundSame, foundExternal)
	}
}

// A future release constraint alone does not exclude parseable source from inventory.
func TestLoadPackageIncludesParseableNewerGoConstraintSource(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": `package sample

const Present = 1
`,
		"future.go": `//go:build go1.99

package sample

const Future = 2
`,
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	for _, file := range loaded.SourceFiles {
		if file.Filename == "future.go" {
			if len(file.Declarations) != 1 || file.Declarations[0].Name != "Future" {
				t.Fatalf("future source declarations = %#v", file.Declarations)
			}
			return
		}
	}
	t.Fatal("parseable future.go was not included in source inventory")
}

// Release-version context supplements a parse failure; it does not preempt parsing.
func TestSourceParseErrorVersionContext(t *testing.T) {
	const parserError = "syntax error from parser"
	tests := []struct {
		name          string
		source        string
		parserVersion string
		wantContext   bool
		wantVersions  []string
	}{
		{
			name: "newer requirement",
			source: `//go:build go1.28

package sample
`,
			parserVersion: "go1.27",
			wantContext:   true,
			wantVersions:  []string{"Go 1.28", "Go 1.27"},
		},
		{
			name: "equal requirement",
			source: `//go:build go1.28

package sample
`,
			parserVersion: "go1.28",
		},
		{
			name: "older requirement",
			source: `//go:build go1.26

package sample
`,
			parserVersion: "go1.27",
		},
		{
			name: "constraint without minimum version",
			source: `//go:build linux && custom

package sample
`,
			parserVersion: "go1.27",
		},
		{
			name: "negated release constraint",
			source: `//go:build !go1.28

package sample
`,
			parserVersion: "go1.27",
		},
		{
			name: "malformed constraint",
			source: `//go:build go1.28 &&

package sample
`,
			parserVersion: "go1.27",
		},
		{
			name: "multiple modern constraints",
			source: `//go:build go1.28
//go:build go1.29

package sample
`,
			parserVersion: "go1.27",
		},
		{
			name: "unavailable parser version",
			source: `//go:build go1.28

package sample
`,
			parserVersion: "",
		},
		{
			name: "multiple legacy constraints use AND semantics",
			source: `// +build go1.28
// +build go1.27

package sample
`,
			parserVersion: "go1.27",
			wantContext:   true,
			wantVersions:  []string{"Go 1.28", "Go 1.27"},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			err := sourceParseError("future.go", []byte(test.source), errors.New(parserError), test.parserVersion)
			message := err.Error()
			if !strings.Contains(message, parserError) {
				t.Fatalf("diagnostic %q does not preserve parser error", message)
			}
			gotContext := strings.Contains(message, "file build constraints require Go")
			if gotContext != test.wantContext {
				t.Fatalf("diagnostic = %q, contextual version message present %v; want %v", message, gotContext, test.wantContext)
			}
			for _, version := range test.wantVersions {
				if !strings.Contains(message, version) {
					t.Errorf("diagnostic %q does not contain %q", message, version)
				}
			}
		})
	}
}

func TestLoadPackageRejectsConflictingProductionPackageVariants(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go":         "package sample\n",
		"records_linux.go":   "package linuxsample\n",
		"records_windows.go": "package windowsSample\n",
	})
	_, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err == nil || !strings.Contains(err.Error(), "conflicting production package names") || !strings.Contains(err.Error(), "records_linux.go") {
		t.Fatalf("error = %v, want source package conflict", err)
	}
}

func TestLoadPackageRejectsUnsupportedDirectiveScopes(t *testing.T) {
	cases := []struct{ name, filename, contents, want string }{
		{"test", "records_test.go", "package sample\n//monoslices:generate name=Test cmp=compare\n", "test files"},
		{"go build", "records.go", "//go:build never\n\npackage sample\n//monoslices:generate name=Never cmp=compare\n", "build-constrained"},
		{"plus build", "records.go", "// +build never\n\npackage sample\n//monoslices:generate name=Never cmp=compare\n", "build-constrained"},
		{"windows", "records_windows.go", "package sample\n//monoslices:generate name=Windows cmp=compare\n", "build-constrained"},
		{"amd64", "records_amd64.go", "package sample\n//monoslices:generate name=AMD cmp=compare\n", "build-constrained"},
		{"linux suffix", "records_linux.go", "package sample\n//monoslices:generate name=Linux cmp=compare\n", "build-constrained"},
		{"linux amd64 suffix", "records_linux_amd64.go", "package sample\n//monoslices:generate name=LinuxAMD cmp=compare\n", "build-constrained"},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			dir := packageDir(t, map[string]string{
				"specializations.go": "package sample\ntype A int\nfunc compare(a,b A) int { return 0 }\n",
				test.filename:        test.contents,
			})
			_, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
			if err == nil || !strings.Contains(err.Error(), test.want) || !strings.Contains(err.Error(), test.filename) {
				t.Fatalf("error=%v", err)
			}
		})
	}
}

func TestLoadPackageCollectsSamePackageTestMetadataOnly(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": `package sample

type Item int
func compare(left, right Item) int { return int(left - right) }
//monoslices:generate name=Items cmp=compare ops=sort
`,
		"records_test.go": `package sample

func ItemsSort() {}
`,
		"external_test.go": `package sample_test

func ItemsSort() {}
`,
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	found := false
	for _, declaration := range includedSourceDeclarations(loaded) {
		if declaration.Name != "ItemsSort" {
			continue
		}
		if declaration.Filename != "records_test.go" || declaration.Constrained {
			t.Fatalf("same-package test declaration = %#v, want unconstrained records_test.go declaration", declaration)
		}
		found = true
	}
	if !found {
		t.Fatalf("source declarations = %#v, want same-package test declaration", includedSourceDeclarations(loaded))
	}
	for _, file := range loaded.SourceFiles {
		if file.ExternalTest {
			continue
		}
		for _, declaration := range file.Declarations {
			if declaration.Filename == "external_test.go" {
				t.Fatalf("external test declaration leaked into included source files: %#v", declaration)
			}
		}
	}
}

func TestLoadPackagePreservesExplicitImportAliasProvenance(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": `package sample

import (
	fmt "fmt"
	h "strings"
	"strconv"
	_ "errors"
	. "unicode"
)

var (
	_ = fmt.Sprintf
	_ = h.Compare
	_ = strconv.Itoa
	_ = IsLetter
)

type Item int

func compare(left, right Item) int { return int(left - right) }
//monoslices:generate name=Items cmp=compare
`,
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	imports := make(map[string]SourceImport)
	for _, imported := range includedSourceImports(loaded) {
		imports[imported.ImportPath] = imported
	}
	checks := []struct {
		path          string
		name          string
		explicitAlias bool
		dot           bool
	}{
		{path: "fmt", name: "fmt", explicitAlias: true},
		{path: "strings", name: "h", explicitAlias: true},
		{path: "strconv", name: ""},
		{path: "unicode", name: ".", explicitAlias: true, dot: true},
	}
	for _, check := range checks {
		imported, ok := imports[check.path]
		if !ok {
			t.Fatalf("source imports = %#v, missing %q", imports, check.path)
		}
		if imported.Name != check.name || imported.ExplicitAlias != check.explicitAlias || imported.Dot != check.dot {
			t.Errorf("import %q = %#v, want name %q explicit alias %v dot %v", check.path, imported, check.name, check.explicitAlias, check.dot)
		}
	}
	if _, ok := imports["errors"]; ok {
		t.Fatalf("blank import should retain existing source policy and not enter bindings: %#v", imports["errors"])
	}
}

func TestLoadPackageRetainsUnresolvedSamePackageTestImportsAndConstraints(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": `package sample

type Item int
func compare(left, right Item) int { return int(left - right) }
//monoslices:generate name=Items cmp=compare ops=sort
`,
		"records_test.go": `package sample

import "example.com/sample/helper"

var _ = ItemsSortHelper.Value(0)
`,
		"records_windows_test.go": `//go:build windows

package sample

import "fmt"

func WindowsTestHelper() { fmt.Println() }
`,
		"helper/helper.go": `package ItemsSortHelper

type Value int
`,
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	foundDeclaration := false
	for _, declaration := range includedSourceDeclarations(loaded) {
		if declaration.Filename == "records_windows_test.go" && declaration.Name == "WindowsTestHelper" {
			if !declaration.Constrained {
				t.Fatalf("constrained same-package test declaration = %#v, want constrained declaration", declaration)
			}
			foundDeclaration = true
		}
	}
	foundDefault := false
	foundConstrained := false
	for _, imported := range includedSourceImports(loaded) {
		if imported.Filename == "records_test.go" && imported.ImportPath == "example.com/sample/helper" {
			if imported.Name != "" || imported.ExplicitAlias || imported.Constrained || !imported.Test || imported.Dot {
				t.Fatalf("same-package test default import = %#v, want unresolved unconstrained test provenance", imported)
			}
			foundDefault = true
		}
		if imported.Filename == "records_windows_test.go" && imported.ImportPath == "fmt" {
			if imported.Name != "" || !imported.Constrained || !imported.Test || imported.Dot {
				t.Fatalf("constrained same-package test import = %#v, want unresolved constrained test provenance", imported)
			}
			foundConstrained = true
		}
	}
	if !foundDeclaration || !foundDefault || !foundConstrained {
		t.Fatalf("source inventory = declarations %#v, imports %#v; want constrained declaration and default/constrained same-package test imports", includedSourceDeclarations(loaded), includedSourceImports(loaded))
	}
}

func TestLoadPackageRejectsDirectiveInCgoSource(t *testing.T) {
	for _, cgoEnabled := range []string{"1", "0"} {
		t.Run("CGO_ENABLED="+cgoEnabled, func(t *testing.T) {
			t.Setenv("CGO_ENABLED", cgoEnabled)
			dir := packageDir(t, map[string]string{
				"specializations.go": `package sample

type Item int
func compare(left, right Item) int { return int(left - right) }
`,
				"cgo.go": `package sample

import "C"

//monoslices:generate name=Items cmp=compare ops=compare
`,
			})
			_, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
			if err == nil || !strings.Contains(err.Error(), "cgo.go") || !strings.Contains(err.Error(), "build-constrained") {
				t.Fatalf("error=%v", err)
			}
		})
	}
}

func TestLoadPackageCollectsImplicitCgoImportBindingsWhenDisabled(t *testing.T) {
	t.Setenv("CGO_ENABLED", "0")
	dir := packageDir(t, map[string]string{
		"records.go": `package sample

type Item int
func compare(left, right Item) int { return int(left - right) }
//monoslices:generate name=Items cmp=compare ops=compare
`,
		"cgo.go": `package sample

/*
#include <stdint.h>
*/
import "C"
import "fmt"
import . "math"
`,
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	found := map[string]bool{}
	for _, imported := range includedSourceImports(loaded) {
		if imported.Filename != "cgo.go" {
			continue
		}
		if !imported.Constrained {
			t.Errorf("implicit cgo import %#v is not constrained", imported)
		}
		switch {
		case imported.ImportPath == "C" && imported.Name == "C":
			found["C"] = true
		case imported.ImportPath == "fmt" && imported.Name == "":
			found["fmt"] = true
		case imported.ImportPath == "math" && imported.Dot:
			found["math dot"] = true
		}
	}
	for _, name := range []string{"C", "fmt", "math dot"} {
		if !found[name] {
			t.Errorf("source imports lacks constrained %s binding: %#v", name, includedSourceImports(loaded))
		}
	}
}

func TestFilenameIsPlatformConstrained(t *testing.T) {
	cases := []struct {
		name string
		want bool
	}{
		{name: "x_linux.go", want: true},
		{name: "x_amd64.go", want: true},
		{name: "x_linux_amd64.go", want: true},
		{name: "x_nacl.go", want: true},
		{name: "x_whatever.go", want: false},
		{name: "linux.go", want: false},
		{name: "amd64.go", want: false},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			got, err := filenameIsPlatformConstrained(test.name)
			if err != nil {
				t.Fatalf("filenameIsPlatformConstrained() error = %v", err)
			}
			if got != test.want {
				t.Fatalf("filenameIsPlatformConstrained() = %v, want %v", got, test.want)
			}
		})
	}
}

func TestLoadPackageAcceptsPlatformNamedFiles(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"specializations.go": "package sample\ntype A int\nfunc compare(a,b A) int { return 0 }\n",
		"linux.go":           "package sample\n//monoslices:generate name=Linux cmp=compare\n",
		"amd64.go":           "package sample\n//monoslices:generate name=AMD cmp=compare\n",
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatal(err)
	}
	if got, want := len(loaded.Directives), 2; got != want {
		t.Fatalf("directive count = %d, want %d", got, want)
	}
}

func TestLoadPackageResolvesInactiveCgoImport(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("the cgo source is active on Windows")
	}
	dir := packageDir(t, map[string]string{
		"specializations.go": `package sample

type Item int
func compare(left, right Item) int { return int(left - right) }
//monoslices:generate name=Items cmp=compare ops=compare
`,
		"cgo_windows.go": `//go:build windows && cgo

package sample

/*
#include <stdint.h>
*/
import "C"

var _ = C.int(0)
`,
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	for _, imported := range includedSourceImports(loaded) {
		if imported.Filename == "cgo_windows.go" && imported.ImportPath == "C" {
			if got, want := imported.Name, "C"; got != want {
				t.Fatalf("inactive cgo import name = %q, want %q", got, want)
			}
			return
		}
	}
	t.Fatalf("source imports = %#v, want inactive cgo import binding", includedSourceImports(loaded))
}

func includedSourceDeclarations(pkg *Package) []SourceDeclaration {
	var declarations []SourceDeclaration
	for _, file := range pkg.SourceFiles {
		if file.ExternalTest {
			continue
		}
		declarations = append(declarations, file.Declarations...)
	}
	return declarations
}

func includedSourceImports(pkg *Package) []SourceImport {
	var imports []SourceImport
	for _, file := range pkg.SourceFiles {
		if file.ExternalTest {
			continue
		}
		imports = append(imports, file.Imports...)
	}
	return imports
}

func TestHasExplicitBuildConstraintUsesHeaderPlacement(t *testing.T) {
	cases := []struct {
		name string
		data string
		want bool
	}{
		{
			name: "go build header",
			data: "//go:build linux\n\npackage sample\n",
			want: true,
		},
		{
			name: "BOM-prefixed go build header",
			data: "\ufeff//go:build linux\n\npackage sample\n",
			want: true,
		},
		{
			name: "BOM-prefixed legacy header",
			data: "\ufeff// +build linux\n\npackage sample\n",
			want: true,
		},
		{
			name: "legacy header",
			data: "// +build linux\n\npackage sample\n",
			want: true,
		},
		{
			name: "legacy without header separator",
			data: "// +build linux\npackage sample\n",
			want: false,
		},
		{
			name: "legacy after package",
			data: "package sample\n\n// +build linux\n",
			want: false,
		},
		{
			name: "legacy in block comment",
			data: "/*\n// +build linux\n*/\n\npackage sample\n",
			want: false,
		},
		{
			name: "go build in block comment",
			data: "/* //go:build linux */\n\npackage sample\n",
			want: false,
		},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			if got := hasExplicitBuildConstraint([]byte(test.data)); got != test.want {
				t.Fatalf("hasExplicitBuildConstraint() = %v, want %v", got, test.want)
			}
		})
	}
}

func TestLoadPackageRejectsBOMPrefixedActiveBuildConstraint(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": "\ufeff//go:build !ignore\n\npackage sample\n//monoslices:generate name=Records cmp=compare\n",
	})
	_, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err == nil || !strings.Contains(err.Error(), "records.go") || !strings.Contains(err.Error(), "build-constrained") {
		t.Fatalf("error=%v", err)
	}
}

func TestLoadPackageRejectsInactiveOnlyDirectiveSource(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": "//go:build never\n\npackage sample\n//monoslices:generate name=Records cmp=compare\n",
	})
	_, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err == nil || !strings.Contains(err.Error(), "records.go") || !strings.Contains(err.Error(), "build-constrained") {
		t.Fatalf("error=%v", err)
	}
}

func TestLoadPackageReportsMalformedDirectivePosition(t *testing.T) {
	dir := packageDir(t, map[string]string{"records.go": "package sample\n\n//monoslices:generate name=Records cmp\n"})
	_, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err == nil || !strings.Contains(err.Error(), "records.go:3:1") || !strings.Contains(err.Error(), "expected '='") {
		t.Fatalf("error=%v", err)
	}
}

func TestLoadPackageCustomOutputAndSymlinkParent(t *testing.T) {
	dir := packageDir(t, map[string]string{"records.go": "package sample\n"})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{Out: "custom.go"})
	if err != nil {
		t.Fatal(err)
	}
	if want := filepath.Join(dir, "custom.go"); loaded.OutputPath != want {
		t.Fatalf("OutputPath=%q", loaded.OutputPath)
	}
	outside := filepath.Join(t.TempDir(), "outside")
	if err := os.Mkdir(outside, 0o755); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(dir, "link")
	if err := os.Symlink(outside, link); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	_, err = LoadPackage(context.Background(), dir, config.CLIConfig{Out: filepath.Join("link", "generated.go")})
	if err == nil || !strings.Contains(err.Error(), "outside package directory") {
		t.Fatalf("error=%v", err)
	}
}

func TestResolveOutputPathRejectsNonProductionBasenames(t *testing.T) {
	dir := packageDir(t, nil)
	for _, name := range []string{"_monoslices.go", ".monoslices.go", "monoslices_test.go", "monoslices_windows.go", "monoslices_amd64.go", "monoslices_nacl.go"} {
		t.Run(name, func(t *testing.T) {
			_, err := resolveOutputPathName(dir, dir, name)
			if err == nil || !strings.Contains(err.Error(), "ordinary production Go source filename") {
				t.Fatalf("resolveOutputPathName(%q) error = %v", name, err)
			}
		})
	}
}

func TestLoadPackageUsesSourcePackageNameAndExcludesOwnedOutput(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go":        "package sample\n",
		"monoslices_gen.go": "// Code generated by monoslices. DO NOT EDIT.\npackage stale\nfunc stale() {}\n",
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	if loaded.Name != "sample" {
		t.Fatalf("package name = %q, want sample", loaded.Name)
	}
	if len(loaded.OwnedFiles) != 1 || filepath.Base(loaded.OwnedFiles[0]) != "monoslices_gen.go" {
		t.Fatalf("owned files = %#v, want monoslices_gen.go", loaded.OwnedFiles)
	}
	for _, file := range loaded.SourceFiles {
		if file.Filename == "monoslices_gen.go" {
			t.Fatal("owned output was included in handwritten source inventory")
		}
	}
}

func TestLoadPackageRetainsConstraintProvenanceWithoutSolving(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": `package sample

type Item int
func compare(left, right Item) int { return int(left - right) }
//monoslices:generate name=Items cmp=compare ops=compare
`,
		"custom_linux.go": `//go:build custom

package sample
`,
		"release_windows.go": `//go:build go1.25

package sample
`,
		"legacy.go": `// +build custom

package sample
`,
		"cgo.go": `//go:build phase7cgo

package sample

import "C"
`,
		"records_nacl.go": "package sample\n",
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v", err)
	}
	want := map[string]struct {
		expression string
		cgo        bool
	}{
		"custom_linux.go":    {expression: "custom"},
		"release_windows.go": {expression: "go1.25"},
		"legacy.go":          {expression: "custom"},
		"cgo.go":             {expression: "phase7cgo", cgo: true},
		"records_nacl.go":    {},
	}
	seen := make(map[string]bool, len(want))
	for _, file := range loaded.SourceFiles {
		check, ok := want[file.Filename]
		if !ok {
			continue
		}
		seen[file.Filename] = true
		if !file.Constraint.Constrained || file.Constraint.GoBuildExpression != check.expression ||
			file.Constraint.RequiresCgo != check.cgo {
			t.Errorf("%s constraint = %#v, want expression %q cgo %v", file.Filename, file.Constraint, check.expression, check.cgo)
		}
	}
	for name := range want {
		if !seen[name] {
			t.Errorf("source inventory lacks %s", name)
		}
	}
}

func TestLoadPackageAcceptsUnresolvedInactiveDefaultImport(t *testing.T) {
	dir := packageDir(t, map[string]string{
		"records.go": `package sample

type Item int
func compare(left, right Item) int { return int(left - right) }
//monoslices:generate name=Items cmp=compare ops=compare
`,
		"records_windows.go": `//go:build windows

package sample

import "example.com/sample/missing"
var _ = missing.Value
`,
	})
	loaded, err := LoadPackage(context.Background(), dir, config.CLIConfig{})
	if err != nil {
		t.Fatalf("LoadPackage() error = %v, want unavailable default import to remain unresolved", err)
	}
	for _, imported := range includedSourceImports(loaded) {
		if imported.Filename != "records_windows.go" || imported.ImportPath != "example.com/sample/missing" {
			continue
		}
		if imported.Name != "" || imported.ExplicitAlias || !imported.Constrained {
			t.Fatalf("inactive default import = %#v, want unresolved name with constraint provenance", imported)
		}
		return
	}
	t.Fatalf("source imports = %#v, want inactive missing import provenance", includedSourceImports(loaded))
}

func packageDir(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/sample\n\ngo 1.24.0\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}
