// Code generated by monoslices. DO NOT EDIT.
//
// Adapted from:
//
//	Go 1.24.0, src/slices/slices.go
//	Go 1.24.0, src/slices/sort.go
//	Go 1.24.0, src/slices/zsortanyfunc.go
//
// Copyright 2026 Zach Olstein. All rights reserved.
// Copyright 2023 The Go Authors. All rights reserved.
// Copyright 2022 The Go Authors. All rights reserved.
// Copyright 2021 The Go Authors. All rights reserved.
//
// Copyright 2009 The Go Authors.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//   - Redistributions of source code must retain the above copyright
//
// notice, this list of conditions and the following disclaimer.
//   - Redistributions in binary form must reproduce the above
//
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//   - Neither the name of Google LLC nor the names of its
//
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
package fuzzfixture

import (
	bits "math/bits"
)

// monoslices: specializations.go name=Ints pred=isInteresting eq=equalInt cmp=compareInt

// IntsContains reports whether any element of s satisfies isInteresting.
func IntsContains(s []int) bool {
	for i := range s {
		if isInteresting(s[i]) {
			return true
		}
	}
	return false
}

// IntsIndex returns the first index i for which isInteresting(s[i]) is true, or -1 if no element satisfies isInteresting.
func IntsIndex(s []int) int {
	for i := range s {
		if isInteresting(s[i]) {
			return i
		}
	}
	return -1
}

// IntsDelete removes elements for which isInteresting is true, modifies s in place, zeroes obsolete tail elements, and returns the shortened slice.
func IntsDelete(s []int) []int {
	i := -1
	for index := range s {
		if isInteresting(s[index]) {
			i = index
			break
		}
	}
	if i == -1 {
		return s
	}
	for j := i + 1; j < len(s); j++ {
		v := s[j]
		if !isInteresting(v) {
			s[i] = v
			i++
		}
	}
	clear(s[i:])
	return s[:i]
}

// IntsCompact removes consecutive runs whose adjacent elements satisfy equalInt, modifies s in place, zeroes obsolete tail elements, and returns the shortened slice.
func IntsCompact(s []int) []int {
	if len(s) < 2 {
		return s
	}
	for k := 1; k < len(s); k++ {
		if equalInt(s[k], s[k-1]) {
			s2 := s[k:]
			for k2 := 1; k2 < len(s2); k2++ {
				if !equalInt(s2[k2], s2[k2-1]) {
					s[k] = s2[k2]
					k++
				}
			}
			clear(s[k:])
			return s[:k]
		}
	}
	return s
}

// IntsEqual reports whether a and b have equal lengths and equalInt reports true for every corresponding pair.
func IntsEqual(a []int, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if !equalInt(a[i], b[i]) {
			return false
		}
	}
	return true
}

// IntsCompare lexicographically compares a and b with comparator compareInt, preserving its first nonzero result and otherwise ordering by length.
func IntsCompare(a []int, b []int) int {
	for i := range a {
		if i >= len(b) {
			return 1
		}
		if c := compareInt(a[i], b[i]); c != 0 {
			return c
		}
	}
	if len(a) < len(b) {
		return -1
	}
	return 0
}

// IntsMin returns the first min element of s according to comparator compareInt (the first element wins ties) and panics if s is empty.
func IntsMin(s []int) int {
	if len(s) < 1 {
		panic("slices.MinFunc: empty list")
	}
	m := s[0]
	for i := 1; i < len(s); i++ {
		if compareInt(s[i], m) < 0 {
			m = s[i]
		}
	}
	return m
}

// IntsMax returns the first max element of s according to comparator compareInt (the first element wins ties) and panics if s is empty.
func IntsMax(s []int) int {
	if len(s) < 1 {
		panic("slices.MaxFunc: empty list")
	}
	m := s[0]
	for i := 1; i < len(s); i++ {
		if compareInt(s[i], m) > 0 {
			m = s[i]
		}
	}
	return m
}

// IntsSort sorts s in place according to comparator compareInt. The comparator must define the strict weak ordering required by slices.SortFunc; this sort is not stable.
func IntsSort(s []int) {
	monoslices_IntsSort_PDQSort_helper(s, 0, len(s), bits.Len(uint(len(s))))
}

// IntsSortStable stably sorts s in place according to comparator compareInt. Equal elements retain their original order. The comparator must define the strict weak ordering required by slices.SortStableFunc.
func IntsSortStable(s []int) {
	monoslices_IntsSort_Stable_helper(s, len(s))
}

// IntsIsSorted reports whether s is sorted according to comparator compareInt. The comparator must define a strict weak ordering.
func IntsIsSorted(s []int) bool {
	for i := len(s) - 1; i > 0; i-- {
		if compareInt(s[i], s[i-1]) < 0 {
			return false
		}
	}
	return true
}

// IntsBinarySearch searches s, which must be sorted according to comparator compareInt, for target. It returns the earliest index where compareInt(s[i], target) is zero and true, or the insertion index and false when no equivalent element exists.
func IntsBinarySearch(s []int, target int) (int, bool) {
	n := len(s)
	i, j := 0, n
	for i < j {
		h := int(uint(i+j) >> 1)
		if compareInt(s[h], target) < 0 {
			i = h + 1
		} else {
			j = h
		}
	}
	return i, i < n && (compareInt(s[i], target) == 0)
}

// monoslices: specializations.go name=RefInts pred=isInterestingRef eq=equalIntRef cmp=compareIntRef byref=true

// RefIntsContains reports whether any element of s satisfies isInterestingRef. The specialization function "isInterestingRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsContains(s []int) bool {
	for i := range s {
		if isInterestingRef(&s[i]) {
			return true
		}
	}
	return false
}

// RefIntsIndex returns the first index i for which isInterestingRef(s[i]) is true, or -1 if no element satisfies isInterestingRef. The specialization function "isInterestingRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsIndex(s []int) int {
	for i := range s {
		if isInterestingRef(&s[i]) {
			return i
		}
	}
	return -1
}

// RefIntsDelete removes elements for which isInterestingRef is true, modifies s in place, zeroes obsolete tail elements, and returns the shortened slice. The specialization function "isInterestingRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsDelete(s []int) []int {
	i := -1
	for index := range s {
		if isInterestingRef(&s[index]) {
			i = index
			break
		}
	}
	if i == -1 {
		return s
	}
	for j := i + 1; j < len(s); j++ {
		if !isInterestingRef(&s[j]) {
			s[i] = s[j]
			i++
		}
	}
	clear(s[i:])
	return s[:i]
}

// RefIntsCompact removes consecutive runs whose adjacent elements satisfy equalIntRef, modifies s in place, zeroes obsolete tail elements, and returns the shortened slice. The specialization function "equalIntRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsCompact(s []int) []int {
	if len(s) < 2 {
		return s
	}
	for k := 1; k < len(s); k++ {
		if equalIntRef(&s[k], &s[k-1]) {
			s2 := s[k:]
			for k2 := 1; k2 < len(s2); k2++ {
				if !equalIntRef(&s2[k2], &s2[k2-1]) {
					s[k] = s2[k2]
					k++
				}
			}
			clear(s[k:])
			return s[:k]
		}
	}
	return s
}

// RefIntsEqual reports whether a and b have equal lengths and equalIntRef reports true for every corresponding pair. The specialization function "equalIntRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsEqual(a []int, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if !equalIntRef(&a[i], &b[i]) {
			return false
		}
	}
	return true
}

// RefIntsCompare lexicographically compares a and b with comparator compareIntRef, preserving its first nonzero result and otherwise ordering by length. The specialization function "compareIntRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsCompare(a []int, b []int) int {
	for i := range a {
		if i >= len(b) {
			return 1
		}
		if c := compareIntRef(&a[i], &b[i]); c != 0 {
			return c
		}
	}
	if len(a) < len(b) {
		return -1
	}
	return 0
}

// RefIntsMin returns the first min element of s according to comparator compareIntRef (the first element wins ties) and panics if s is empty. The specialization function "compareIntRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsMin(s []int) int {
	if len(s) < 1 {
		panic("slices.MinFunc: empty list")
	}
	best := &s[0]
	for i := 1; i < len(s); i++ {
		if compareIntRef(&s[i], best) < 0 {
			best = &s[i]
		}
	}
	return *best
}

// RefIntsMax returns the first max element of s according to comparator compareIntRef (the first element wins ties) and panics if s is empty. The specialization function "compareIntRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsMax(s []int) int {
	if len(s) < 1 {
		panic("slices.MaxFunc: empty list")
	}
	best := &s[0]
	for i := 1; i < len(s); i++ {
		if compareIntRef(&s[i], best) > 0 {
			best = &s[i]
		}
	}
	return *best
}

// RefIntsSort sorts s in place according to comparator compareIntRef. The comparator must define the strict weak ordering required by slices.SortFunc; this sort is not stable. The specialization function "compareIntRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsSort(s []int) {
	monoslices_RefIntsSort_PDQSort_helper(s, 0, len(s), bits.Len(uint(len(s))))
}

// RefIntsSortStable stably sorts s in place according to comparator compareIntRef. Equal elements retain their original order. The comparator must define the strict weak ordering required by slices.SortStableFunc. The specialization function "compareIntRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsSortStable(s []int) {
	monoslices_RefIntsSort_Stable_helper(s, len(s))
}

// RefIntsIsSorted reports whether s is sorted according to comparator compareIntRef. The comparator must define a strict weak ordering. The specialization function "compareIntRef" receives selected slice elements through pointers to live slice slots; treat them as read-only unless the function intentionally accounts for their aliasing.
func RefIntsIsSorted(s []int) bool {
	for i := len(s) - 1; i > 0; i-- {
		if compareIntRef(&s[i], &s[i-1]) < 0 {
			return false
		}
	}
	return true
}

// RefIntsBinarySearch searches s, which must be sorted according to comparator compareIntRef, for target. It returns the earliest index where compareIntRef(s[i], target) is zero and true, or the insertion index and false when no equivalent element exists. The specialization function "compareIntRef" receives an ordinary pointer to the slice element; the target is passed as declared.
func RefIntsBinarySearch(s []int, target *int) (int, bool) {
	n := len(s)
	i, j := 0, n
	for i < j {
		h := int(uint(i+j) >> 1)
		if compareIntRef(&s[h], target) < 0 {
			i = h + 1
		} else {
			j = h
		}
	}
	return i, i < n && (compareIntRef(&s[i], target) == 0)
}

// monoslices: specializations.go name=Records cmp=compareRecord ops=sort,sort-stable

// RecordsSort sorts s in place according to comparator compareRecord. The comparator must define the strict weak ordering required by slices.SortFunc; this sort is not stable.
func RecordsSort(s []Record) {
	monoslices_RecordsSort_PDQSort_helper(s, 0, len(s), bits.Len(uint(len(s))))
}

// RecordsSortStable stably sorts s in place according to comparator compareRecord. Equal elements retain their original order. The comparator must define the strict weak ordering required by slices.SortStableFunc.
func RecordsSortStable(s []Record) {
	monoslices_RecordsSort_Stable_helper(s, len(s))
}

// monoslices: specializations.go name=RecordKeys cmp=compareRecordKey ops=binary-search

// RecordKeysBinarySearch searches s, which must be sorted according to comparator compareRecordKey, for target. It returns the earliest index where compareRecordKey(s[i], target) is zero and true, or the insertion index and false when no equivalent element exists.
func RecordKeysBinarySearch(s []Record, target SearchKey) (int, bool) {
	n := len(s)
	i, j := 0, n
	for i < j {
		h := int(uint(i+j) >> 1)
		if compareRecordKey(s[h], target) < 0 {
			i = h + 1
		} else {
			j = h
		}
	}
	return i, i < n && (compareRecordKey(s[i], target) == 0)
}

// monoslices: specializations.go name=RefRecordKeys cmp=compareRecordKeyRef byref=first ops=binary-search

// RefRecordKeysBinarySearch searches s, which must be sorted according to comparator compareRecordKeyRef, for target. It returns the earliest index where compareRecordKeyRef(s[i], target) is zero and true, or the insertion index and false when no equivalent element exists. The specialization function "compareRecordKeyRef" receives an ordinary pointer to the slice element; the target is passed as declared.
func RefRecordKeysBinarySearch(s []Record, target SearchKey) (int, bool) {
	n := len(s)
	i, j := 0, n
	for i < j {
		h := int(uint(i+j) >> 1)
		if compareRecordKeyRef(&s[h], target) < 0 {
			i = h + 1
		} else {
			j = h
		}
	}
	return i, i < n && (compareRecordKeyRef(&s[i], target) == 0)
}

// monoslices: specializations.go name=Weird eq=weirdEqual ops=compact

// WeirdCompact removes consecutive runs whose adjacent elements satisfy weirdEqual, modifies s in place, zeroes obsolete tail elements, and returns the shortened slice.
func WeirdCompact(s []int) []int {
	if len(s) < 2 {
		return s
	}
	for k := 1; k < len(s); k++ {
		if weirdEqual(s[k], s[k-1]) {
			s2 := s[k:]
			for k2 := 1; k2 < len(s2); k2++ {
				if !weirdEqual(s2[k2], s2[k2-1]) {
					s[k] = s2[k2]
					k++
				}
			}
			clear(s[k:])
			return s[:k]
		}
	}
	return s
}

func monoslices_IntsSort_InsertionSort_helper(data []int, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && (compareInt(data[j], data[j-1]) < 0); j-- {
			data[j], data[j-1] = data[j-1], data[j]
		}
	}
}

func monoslices_IntsSort_SiftDown_helper(data []int, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && (compareInt(data[first+child], data[first+child+1]) < 0) {
			child++
		}
		if !(compareInt(data[first+root], data[first+child]) < 0) {
			return
		}
		data[first+root], data[first+child] = data[first+child], data[first+root]
		root = child
	}
}

func monoslices_IntsSort_HeapSort_helper(data []int, a, b int) {
	first := a
	lo := 0
	hi := b - a
	for i := (hi - 1) / 2; i >= 0; i-- {
		monoslices_IntsSort_SiftDown_helper(data, i, hi, first)
	}
	for i := hi - 1; i >= 0; i-- {
		data[first], data[first+i] = data[first+i], data[first]
		monoslices_IntsSort_SiftDown_helper(data, lo, i, first)
	}
}

func monoslices_IntsSort_PDQSort_helper(data []int, a, b, limit int) {
	const maxInsertion = 12
	var (
		wasBalanced    = true
		wasPartitioned = true
	)
	for {
		length := b - a
		if length <= maxInsertion {
			monoslices_IntsSort_InsertionSort_helper(data, a, b)
			return
		}
		if limit == 0 {
			monoslices_IntsSort_HeapSort_helper(data, a, b)
			return
		}
		if !wasBalanced {
			monoslices_IntsSort_BreakPatterns_helper(data, a, b)
			limit--
		}
		pivot, hint := monoslices_IntsSort_ChoosePivot_helper(data, a, b)
		if hint == monoslices_IntsSort_DecreasingHint_helper {
			monoslices_IntsSort_ReverseRange_helper(data, a, b)
			pivot = (b - 1) - (pivot - a)
			hint = monoslices_IntsSort_IncreasingHint_helper
		}
		if wasBalanced && wasPartitioned && hint == monoslices_IntsSort_IncreasingHint_helper {
			if monoslices_IntsSort_PartialInsertionSort_helper(data, a, b) {
				return
			}
		}
		if a > 0 && !(compareInt(data[a-1], data[pivot]) < 0) {
			mid := monoslices_IntsSort_PartitionEqual_helper(data, a, b, pivot)
			a = mid
			continue
		}
		mid, alreadyPartitioned := monoslices_IntsSort_Partition_helper(data, a, b, pivot)
		wasPartitioned = alreadyPartitioned
		leftLen, rightLen := mid-a, b-mid
		balanceThreshold := length / 8
		if leftLen < rightLen {
			wasBalanced = leftLen >= balanceThreshold
			monoslices_IntsSort_PDQSort_helper(data, a, mid, limit)
			a = mid + 1
		} else {
			wasBalanced = rightLen >= balanceThreshold
			monoslices_IntsSort_PDQSort_helper(data, mid+1, b, limit)
			b = mid
		}
	}
}

func monoslices_IntsSort_Partition_helper(data []int, a, b, pivot int) (int, bool) {
	data[a], data[pivot] = data[pivot], data[a]
	i, j := a+1, b-1
	for i <= j && (compareInt(data[i], data[a]) < 0) {
		i++
	}
	for i <= j && !(compareInt(data[j], data[a]) < 0) {
		j--
	}
	if i > j {
		data[j], data[a] = data[a], data[j]
		return j, true
	}
	data[i], data[j] = data[j], data[i]
	i++
	j--
	for {
		for i <= j && (compareInt(data[i], data[a]) < 0) {
			i++
		}
		for i <= j && !(compareInt(data[j], data[a]) < 0) {
			j--
		}
		if i > j {
			break
		}
		data[i], data[j] = data[j], data[i]
		i++
		j--
	}
	data[j], data[a] = data[a], data[j]
	return j, false
}

func monoslices_IntsSort_PartitionEqual_helper(data []int, a, b, pivot int) int {
	data[a], data[pivot] = data[pivot], data[a]
	i, j := a+1, b-1
	for {
		for i <= j && !(compareInt(data[a], data[i]) < 0) {
			i++
		}
		for i <= j && (compareInt(data[a], data[j]) < 0) {
			j--
		}
		if i > j {
			break
		}
		data[i], data[j] = data[j], data[i]
		i++
		j--
	}
	return i
}

func monoslices_IntsSort_PartialInsertionSort_helper(data []int, a, b int) bool {
	const (
		maxSteps         = 5
		shortestShifting = 50
	)
	i := a + 1
	for j := 0; j < maxSteps; j++ {
		for i < b && !(compareInt(data[i], data[i-1]) < 0) {
			i++
		}
		if i == b {
			return true
		}
		if b-a < shortestShifting {
			return false
		}
		data[i], data[i-1] = data[i-1], data[i]
		if i-a >= 2 {
			for j := i - 1; j >= 1; j-- {
				if !(compareInt(data[j], data[j-1]) < 0) {
					break
				}
				data[j], data[j-1] = data[j-1], data[j]
			}
		}
		if b-i >= 2 {
			for j := i + 1; j < b; j++ {
				if !(compareInt(data[j], data[j-1]) < 0) {
					break
				}
				data[j], data[j-1] = data[j-1], data[j]
			}
		}
	}
	return false
}

func monoslices_IntsSort_BreakPatterns_helper(data []int, a, b int) {
	length := b - a
	if length >= 8 {
		random := monoslices_IntsSort_Xorshift_helper(length)
		modulus := monoslices_IntsSort_NextPowerOfTwo_helper(length)
		for idx := a + (length/4)*2 - 1; idx <= a+(length/4)*2+1; idx++ {
			other := int(uint(random.Next()) & (modulus - 1))
			if other >= length {
				other -= length
			}
			data[idx], data[a+other] = data[a+other], data[idx]
		}
	}
}

func monoslices_IntsSort_ChoosePivot_helper(data []int, a, b int) (int, monoslices_IntsSort_SortedHint_helper) {
	const (
		shortestNinther = 50
		maxSwaps        = 4 * 3
	)
	l := b - a
	var (
		swaps int
		i     = a + l/4*1
		j     = a + l/4*2
		k     = a + l/4*3
	)
	if l >= 8 {
		if l >= shortestNinther {
			i = monoslices_IntsSort_MedianAdjacent_helper(data, i, &swaps)
			j = monoslices_IntsSort_MedianAdjacent_helper(data, j, &swaps)
			k = monoslices_IntsSort_MedianAdjacent_helper(data, k, &swaps)
		}
		j = monoslices_IntsSort_Median_helper(data, i, j, k, &swaps)
	}
	switch swaps {
	case 0:
		return j, monoslices_IntsSort_IncreasingHint_helper
	case maxSwaps:
		return j, monoslices_IntsSort_DecreasingHint_helper
	default:
		return j, monoslices_IntsSort_UnknownHint_helper
	}
}

func monoslices_IntsSort_Order2_helper(data []int, a, b int, swaps *int) (int, int) {
	if compareInt(data[b], data[a]) < 0 {
		*swaps++
		return b, a
	}
	return a, b
}

func monoslices_IntsSort_Median_helper(data []int, a, b, c int, swaps *int) int {
	a, b = monoslices_IntsSort_Order2_helper(data, a, b, swaps)
	b, c = monoslices_IntsSort_Order2_helper(data, b, c, swaps)
	a, b = monoslices_IntsSort_Order2_helper(data, a, b, swaps)
	return b
}

func monoslices_IntsSort_MedianAdjacent_helper(data []int, a int, swaps *int) int {
	return monoslices_IntsSort_Median_helper(data, a-1, a, a+1, swaps)
}

func monoslices_IntsSort_ReverseRange_helper(data []int, a, b int) {
	i, j := a, b-1
	for i < j {
		data[i], data[j] = data[j], data[i]
		i++
		j--
	}
}

func monoslices_IntsSort_Stable_helper(data []int, n int) {
	blockSize := 20
	a, b := 0, blockSize
	for b <= n {
		monoslices_IntsSort_InsertionSort_helper(data, a, b)
		a = b
		b += blockSize
	}
	monoslices_IntsSort_InsertionSort_helper(data, a, n)
	for blockSize < n {
		a, b = 0, 2*blockSize
		for b <= n {
			monoslices_IntsSort_SymMerge_helper(data, a, a+blockSize, b)
			a = b
			b += 2 * blockSize
		}
		if m := a + blockSize; m < n {
			monoslices_IntsSort_SymMerge_helper(data, a, m, n)
		}
		blockSize *= 2
	}
}

func monoslices_IntsSort_SymMerge_helper(data []int, a, m, b int) {
	if m-a == 1 {
		i, j := m, b
		for i < j {
			h := int(uint(i+j) >> 1)
			if compareInt(data[h], data[a]) < 0 {
				i = h + 1
			} else {
				j = h
			}
		}
		for k := a; k < i-1; k++ {
			data[k], data[k+1] = data[k+1], data[k]
		}
		return
	}
	if b-m == 1 {
		i, j := a, m
		for i < j {
			h := int(uint(i+j) >> 1)
			if !(compareInt(data[m], data[h]) < 0) {
				i = h + 1
			} else {
				j = h
			}
		}
		for k := m; k > i; k-- {
			data[k], data[k-1] = data[k-1], data[k]
		}
		return
	}
	mid := int(uint(a+b) >> 1)
	n := mid + m
	var start, r int
	if m > mid {
		start = n - b
		r = mid
	} else {
		start = a
		r = m
	}
	p := n - 1
	for start < r {
		c := int(uint(start+r) >> 1)
		if !(compareInt(data[p-c], data[c]) < 0) {
			start = c + 1
		} else {
			r = c
		}
	}
	end := n - start
	if start < m && m < end {
		monoslices_IntsSort_Rotate_helper(data, start, m, end)
	}
	if a < start && start < mid {
		monoslices_IntsSort_SymMerge_helper(data, a, start, mid)
	}
	if mid < end && end < b {
		monoslices_IntsSort_SymMerge_helper(data, mid, end, b)
	}
}

func monoslices_IntsSort_Rotate_helper(data []int, a, m, b int) {
	i, j := m-a, b-m
	for i != j {
		if i > j {
			monoslices_IntsSort_SwapRange_helper(data, m-i, m, j)
			i -= j
		} else {
			monoslices_IntsSort_SwapRange_helper(data, m-i, m+j-i, i)
			j -= i
		}
	}
	monoslices_IntsSort_SwapRange_helper(data, m-i, m, i)
}

func monoslices_IntsSort_SwapRange_helper(data []int, a, b, n int) {
	for i := 0; i < n; i++ {
		data[a+i], data[b+i] = data[b+i], data[a+i]
	}
}

func monoslices_RefIntsSort_InsertionSort_helper(data []int, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && (compareIntRef(&data[j], &data[j-1]) < 0); j-- {
			data[j], data[j-1] = data[j-1], data[j]
		}
	}
}

func monoslices_RefIntsSort_SiftDown_helper(data []int, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && (compareIntRef(&data[first+child], &data[first+child+1]) < 0) {
			child++
		}
		if !(compareIntRef(&data[first+root], &data[first+child]) < 0) {
			return
		}
		data[first+root], data[first+child] = data[first+child], data[first+root]
		root = child
	}
}

func monoslices_RefIntsSort_HeapSort_helper(data []int, a, b int) {
	first := a
	lo := 0
	hi := b - a
	for i := (hi - 1) / 2; i >= 0; i-- {
		monoslices_RefIntsSort_SiftDown_helper(data, i, hi, first)
	}
	for i := hi - 1; i >= 0; i-- {
		data[first], data[first+i] = data[first+i], data[first]
		monoslices_RefIntsSort_SiftDown_helper(data, lo, i, first)
	}
}

func monoslices_RefIntsSort_PDQSort_helper(data []int, a, b, limit int) {
	const maxInsertion = 12
	var (
		wasBalanced    = true
		wasPartitioned = true
	)
	for {
		length := b - a
		if length <= maxInsertion {
			monoslices_RefIntsSort_InsertionSort_helper(data, a, b)
			return
		}
		if limit == 0 {
			monoslices_RefIntsSort_HeapSort_helper(data, a, b)
			return
		}
		if !wasBalanced {
			monoslices_RefIntsSort_BreakPatterns_helper(data, a, b)
			limit--
		}
		pivot, hint := monoslices_RefIntsSort_ChoosePivot_helper(data, a, b)
		if hint == monoslices_IntsSort_DecreasingHint_helper {
			monoslices_RefIntsSort_ReverseRange_helper(data, a, b)
			pivot = (b - 1) - (pivot - a)
			hint = monoslices_IntsSort_IncreasingHint_helper
		}
		if wasBalanced && wasPartitioned && hint == monoslices_IntsSort_IncreasingHint_helper {
			if monoslices_RefIntsSort_PartialInsertionSort_helper(data, a, b) {
				return
			}
		}
		if a > 0 && !(compareIntRef(&data[a-1], &data[pivot]) < 0) {
			mid := monoslices_RefIntsSort_PartitionEqual_helper(data, a, b, pivot)
			a = mid
			continue
		}
		mid, alreadyPartitioned := monoslices_RefIntsSort_Partition_helper(data, a, b, pivot)
		wasPartitioned = alreadyPartitioned
		leftLen, rightLen := mid-a, b-mid
		balanceThreshold := length / 8
		if leftLen < rightLen {
			wasBalanced = leftLen >= balanceThreshold
			monoslices_RefIntsSort_PDQSort_helper(data, a, mid, limit)
			a = mid + 1
		} else {
			wasBalanced = rightLen >= balanceThreshold
			monoslices_RefIntsSort_PDQSort_helper(data, mid+1, b, limit)
			b = mid
		}
	}
}

func monoslices_RefIntsSort_Partition_helper(data []int, a, b, pivot int) (int, bool) {
	data[a], data[pivot] = data[pivot], data[a]
	i, j := a+1, b-1
	for i <= j && (compareIntRef(&data[i], &data[a]) < 0) {
		i++
	}
	for i <= j && !(compareIntRef(&data[j], &data[a]) < 0) {
		j--
	}
	if i > j {
		data[j], data[a] = data[a], data[j]
		return j, true
	}
	data[i], data[j] = data[j], data[i]
	i++
	j--
	for {
		for i <= j && (compareIntRef(&data[i], &data[a]) < 0) {
			i++
		}
		for i <= j && !(compareIntRef(&data[j], &data[a]) < 0) {
			j--
		}
		if i > j {
			break
		}
		data[i], data[j] = data[j], data[i]
		i++
		j--
	}
	data[j], data[a] = data[a], data[j]
	return j, false
}

func monoslices_RefIntsSort_PartitionEqual_helper(data []int, a, b, pivot int) int {
	data[a], data[pivot] = data[pivot], data[a]
	i, j := a+1, b-1
	for {
		for i <= j && !(compareIntRef(&data[a], &data[i]) < 0) {
			i++
		}
		for i <= j && (compareIntRef(&data[a], &data[j]) < 0) {
			j--
		}
		if i > j {
			break
		}
		data[i], data[j] = data[j], data[i]
		i++
		j--
	}
	return i
}

func monoslices_RefIntsSort_PartialInsertionSort_helper(data []int, a, b int) bool {
	const (
		maxSteps         = 5
		shortestShifting = 50
	)
	i := a + 1
	for j := 0; j < maxSteps; j++ {
		for i < b && !(compareIntRef(&data[i], &data[i-1]) < 0) {
			i++
		}
		if i == b {
			return true
		}
		if b-a < shortestShifting {
			return false
		}
		data[i], data[i-1] = data[i-1], data[i]
		if i-a >= 2 {
			for j := i - 1; j >= 1; j-- {
				if !(compareIntRef(&data[j], &data[j-1]) < 0) {
					break
				}
				data[j], data[j-1] = data[j-1], data[j]
			}
		}
		if b-i >= 2 {
			for j := i + 1; j < b; j++ {
				if !(compareIntRef(&data[j], &data[j-1]) < 0) {
					break
				}
				data[j], data[j-1] = data[j-1], data[j]
			}
		}
	}
	return false
}

func monoslices_RefIntsSort_BreakPatterns_helper(data []int, a, b int) {
	length := b - a
	if length >= 8 {
		random := monoslices_IntsSort_Xorshift_helper(length)
		modulus := monoslices_IntsSort_NextPowerOfTwo_helper(length)
		for idx := a + (length/4)*2 - 1; idx <= a+(length/4)*2+1; idx++ {
			other := int(uint(random.Next()) & (modulus - 1))
			if other >= length {
				other -= length
			}
			data[idx], data[a+other] = data[a+other], data[idx]
		}
	}
}

func monoslices_RefIntsSort_ChoosePivot_helper(data []int, a, b int) (int, monoslices_IntsSort_SortedHint_helper) {
	const (
		shortestNinther = 50
		maxSwaps        = 4 * 3
	)
	l := b - a
	var (
		swaps int
		i     = a + l/4*1
		j     = a + l/4*2
		k     = a + l/4*3
	)
	if l >= 8 {
		if l >= shortestNinther {
			i = monoslices_RefIntsSort_MedianAdjacent_helper(data, i, &swaps)
			j = monoslices_RefIntsSort_MedianAdjacent_helper(data, j, &swaps)
			k = monoslices_RefIntsSort_MedianAdjacent_helper(data, k, &swaps)
		}
		j = monoslices_RefIntsSort_Median_helper(data, i, j, k, &swaps)
	}
	switch swaps {
	case 0:
		return j, monoslices_IntsSort_IncreasingHint_helper
	case maxSwaps:
		return j, monoslices_IntsSort_DecreasingHint_helper
	default:
		return j, monoslices_IntsSort_UnknownHint_helper
	}
}

func monoslices_RefIntsSort_Order2_helper(data []int, a, b int, swaps *int) (int, int) {
	if compareIntRef(&data[b], &data[a]) < 0 {
		*swaps++
		return b, a
	}
	return a, b
}

func monoslices_RefIntsSort_Median_helper(data []int, a, b, c int, swaps *int) int {
	a, b = monoslices_RefIntsSort_Order2_helper(data, a, b, swaps)
	b, c = monoslices_RefIntsSort_Order2_helper(data, b, c, swaps)
	a, b = monoslices_RefIntsSort_Order2_helper(data, a, b, swaps)
	return b
}

func monoslices_RefIntsSort_MedianAdjacent_helper(data []int, a int, swaps *int) int {
	return monoslices_RefIntsSort_Median_helper(data, a-1, a, a+1, swaps)
}

func monoslices_RefIntsSort_ReverseRange_helper(data []int, a, b int) {
	i, j := a, b-1
	for i < j {
		data[i], data[j] = data[j], data[i]
		i++
		j--
	}
}

func monoslices_RefIntsSort_Stable_helper(data []int, n int) {
	blockSize := 20
	a, b := 0, blockSize
	for b <= n {
		monoslices_RefIntsSort_InsertionSort_helper(data, a, b)
		a = b
		b += blockSize
	}
	monoslices_RefIntsSort_InsertionSort_helper(data, a, n)
	for blockSize < n {
		a, b = 0, 2*blockSize
		for b <= n {
			monoslices_RefIntsSort_SymMerge_helper(data, a, a+blockSize, b)
			a = b
			b += 2 * blockSize
		}
		if m := a + blockSize; m < n {
			monoslices_RefIntsSort_SymMerge_helper(data, a, m, n)
		}
		blockSize *= 2
	}
}

func monoslices_RefIntsSort_SymMerge_helper(data []int, a, m, b int) {
	if m-a == 1 {
		i, j := m, b
		for i < j {
			h := int(uint(i+j) >> 1)
			if compareIntRef(&data[h], &data[a]) < 0 {
				i = h + 1
			} else {
				j = h
			}
		}
		for k := a; k < i-1; k++ {
			data[k], data[k+1] = data[k+1], data[k]
		}
		return
	}
	if b-m == 1 {
		i, j := a, m
		for i < j {
			h := int(uint(i+j) >> 1)
			if !(compareIntRef(&data[m], &data[h]) < 0) {
				i = h + 1
			} else {
				j = h
			}
		}
		for k := m; k > i; k-- {
			data[k], data[k-1] = data[k-1], data[k]
		}
		return
	}
	mid := int(uint(a+b) >> 1)
	n := mid + m
	var start, r int
	if m > mid {
		start = n - b
		r = mid
	} else {
		start = a
		r = m
	}
	p := n - 1
	for start < r {
		c := int(uint(start+r) >> 1)
		if !(compareIntRef(&data[p-c], &data[c]) < 0) {
			start = c + 1
		} else {
			r = c
		}
	}
	end := n - start
	if start < m && m < end {
		monoslices_RefIntsSort_Rotate_helper(data, start, m, end)
	}
	if a < start && start < mid {
		monoslices_RefIntsSort_SymMerge_helper(data, a, start, mid)
	}
	if mid < end && end < b {
		monoslices_RefIntsSort_SymMerge_helper(data, mid, end, b)
	}
}

func monoslices_RefIntsSort_Rotate_helper(data []int, a, m, b int) {
	i, j := m-a, b-m
	for i != j {
		if i > j {
			monoslices_RefIntsSort_SwapRange_helper(data, m-i, m, j)
			i -= j
		} else {
			monoslices_RefIntsSort_SwapRange_helper(data, m-i, m+j-i, i)
			j -= i
		}
	}
	monoslices_RefIntsSort_SwapRange_helper(data, m-i, m, i)
}

func monoslices_RefIntsSort_SwapRange_helper(data []int, a, b, n int) {
	for i := 0; i < n; i++ {
		data[a+i], data[b+i] = data[b+i], data[a+i]
	}
}

func monoslices_RecordsSort_InsertionSort_helper(data []Record, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && (compareRecord(data[j], data[j-1]) < 0); j-- {
			data[j], data[j-1] = data[j-1], data[j]
		}
	}
}

func monoslices_RecordsSort_SiftDown_helper(data []Record, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && (compareRecord(data[first+child], data[first+child+1]) < 0) {
			child++
		}
		if !(compareRecord(data[first+root], data[first+child]) < 0) {
			return
		}
		data[first+root], data[first+child] = data[first+child], data[first+root]
		root = child
	}
}

func monoslices_RecordsSort_HeapSort_helper(data []Record, a, b int) {
	first := a
	lo := 0
	hi := b - a
	for i := (hi - 1) / 2; i >= 0; i-- {
		monoslices_RecordsSort_SiftDown_helper(data, i, hi, first)
	}
	for i := hi - 1; i >= 0; i-- {
		data[first], data[first+i] = data[first+i], data[first]
		monoslices_RecordsSort_SiftDown_helper(data, lo, i, first)
	}
}

func monoslices_RecordsSort_PDQSort_helper(data []Record, a, b, limit int) {
	const maxInsertion = 12
	var (
		wasBalanced    = true
		wasPartitioned = true
	)
	for {
		length := b - a
		if length <= maxInsertion {
			monoslices_RecordsSort_InsertionSort_helper(data, a, b)
			return
		}
		if limit == 0 {
			monoslices_RecordsSort_HeapSort_helper(data, a, b)
			return
		}
		if !wasBalanced {
			monoslices_RecordsSort_BreakPatterns_helper(data, a, b)
			limit--
		}
		pivot, hint := monoslices_RecordsSort_ChoosePivot_helper(data, a, b)
		if hint == monoslices_IntsSort_DecreasingHint_helper {
			monoslices_RecordsSort_ReverseRange_helper(data, a, b)
			pivot = (b - 1) - (pivot - a)
			hint = monoslices_IntsSort_IncreasingHint_helper
		}
		if wasBalanced && wasPartitioned && hint == monoslices_IntsSort_IncreasingHint_helper {
			if monoslices_RecordsSort_PartialInsertionSort_helper(data, a, b) {
				return
			}
		}
		if a > 0 && !(compareRecord(data[a-1], data[pivot]) < 0) {
			mid := monoslices_RecordsSort_PartitionEqual_helper(data, a, b, pivot)
			a = mid
			continue
		}
		mid, alreadyPartitioned := monoslices_RecordsSort_Partition_helper(data, a, b, pivot)
		wasPartitioned = alreadyPartitioned
		leftLen, rightLen := mid-a, b-mid
		balanceThreshold := length / 8
		if leftLen < rightLen {
			wasBalanced = leftLen >= balanceThreshold
			monoslices_RecordsSort_PDQSort_helper(data, a, mid, limit)
			a = mid + 1
		} else {
			wasBalanced = rightLen >= balanceThreshold
			monoslices_RecordsSort_PDQSort_helper(data, mid+1, b, limit)
			b = mid
		}
	}
}

func monoslices_RecordsSort_Partition_helper(data []Record, a, b, pivot int) (int, bool) {
	data[a], data[pivot] = data[pivot], data[a]
	i, j := a+1, b-1
	for i <= j && (compareRecord(data[i], data[a]) < 0) {
		i++
	}
	for i <= j && !(compareRecord(data[j], data[a]) < 0) {
		j--
	}
	if i > j {
		data[j], data[a] = data[a], data[j]
		return j, true
	}
	data[i], data[j] = data[j], data[i]
	i++
	j--
	for {
		for i <= j && (compareRecord(data[i], data[a]) < 0) {
			i++
		}
		for i <= j && !(compareRecord(data[j], data[a]) < 0) {
			j--
		}
		if i > j {
			break
		}
		data[i], data[j] = data[j], data[i]
		i++
		j--
	}
	data[j], data[a] = data[a], data[j]
	return j, false
}

func monoslices_RecordsSort_PartitionEqual_helper(data []Record, a, b, pivot int) int {
	data[a], data[pivot] = data[pivot], data[a]
	i, j := a+1, b-1
	for {
		for i <= j && !(compareRecord(data[a], data[i]) < 0) {
			i++
		}
		for i <= j && (compareRecord(data[a], data[j]) < 0) {
			j--
		}
		if i > j {
			break
		}
		data[i], data[j] = data[j], data[i]
		i++
		j--
	}
	return i
}

func monoslices_RecordsSort_PartialInsertionSort_helper(data []Record, a, b int) bool {
	const (
		maxSteps         = 5
		shortestShifting = 50
	)
	i := a + 1
	for j := 0; j < maxSteps; j++ {
		for i < b && !(compareRecord(data[i], data[i-1]) < 0) {
			i++
		}
		if i == b {
			return true
		}
		if b-a < shortestShifting {
			return false
		}
		data[i], data[i-1] = data[i-1], data[i]
		if i-a >= 2 {
			for j := i - 1; j >= 1; j-- {
				if !(compareRecord(data[j], data[j-1]) < 0) {
					break
				}
				data[j], data[j-1] = data[j-1], data[j]
			}
		}
		if b-i >= 2 {
			for j := i + 1; j < b; j++ {
				if !(compareRecord(data[j], data[j-1]) < 0) {
					break
				}
				data[j], data[j-1] = data[j-1], data[j]
			}
		}
	}
	return false
}

func monoslices_RecordsSort_BreakPatterns_helper(data []Record, a, b int) {
	length := b - a
	if length >= 8 {
		random := monoslices_IntsSort_Xorshift_helper(length)
		modulus := monoslices_IntsSort_NextPowerOfTwo_helper(length)
		for idx := a + (length/4)*2 - 1; idx <= a+(length/4)*2+1; idx++ {
			other := int(uint(random.Next()) & (modulus - 1))
			if other >= length {
				other -= length
			}
			data[idx], data[a+other] = data[a+other], data[idx]
		}
	}
}

func monoslices_RecordsSort_ChoosePivot_helper(data []Record, a, b int) (int, monoslices_IntsSort_SortedHint_helper) {
	const (
		shortestNinther = 50
		maxSwaps        = 4 * 3
	)
	l := b - a
	var (
		swaps int
		i     = a + l/4*1
		j     = a + l/4*2
		k     = a + l/4*3
	)
	if l >= 8 {
		if l >= shortestNinther {
			i = monoslices_RecordsSort_MedianAdjacent_helper(data, i, &swaps)
			j = monoslices_RecordsSort_MedianAdjacent_helper(data, j, &swaps)
			k = monoslices_RecordsSort_MedianAdjacent_helper(data, k, &swaps)
		}
		j = monoslices_RecordsSort_Median_helper(data, i, j, k, &swaps)
	}
	switch swaps {
	case 0:
		return j, monoslices_IntsSort_IncreasingHint_helper
	case maxSwaps:
		return j, monoslices_IntsSort_DecreasingHint_helper
	default:
		return j, monoslices_IntsSort_UnknownHint_helper
	}
}

func monoslices_RecordsSort_Order2_helper(data []Record, a, b int, swaps *int) (int, int) {
	if compareRecord(data[b], data[a]) < 0 {
		*swaps++
		return b, a
	}
	return a, b
}

func monoslices_RecordsSort_Median_helper(data []Record, a, b, c int, swaps *int) int {
	a, b = monoslices_RecordsSort_Order2_helper(data, a, b, swaps)
	b, c = monoslices_RecordsSort_Order2_helper(data, b, c, swaps)
	a, b = monoslices_RecordsSort_Order2_helper(data, a, b, swaps)
	return b
}

func monoslices_RecordsSort_MedianAdjacent_helper(data []Record, a int, swaps *int) int {
	return monoslices_RecordsSort_Median_helper(data, a-1, a, a+1, swaps)
}

func monoslices_RecordsSort_ReverseRange_helper(data []Record, a, b int) {
	i, j := a, b-1
	for i < j {
		data[i], data[j] = data[j], data[i]
		i++
		j--
	}
}

func monoslices_RecordsSort_Stable_helper(data []Record, n int) {
	blockSize := 20
	a, b := 0, blockSize
	for b <= n {
		monoslices_RecordsSort_InsertionSort_helper(data, a, b)
		a = b
		b += blockSize
	}
	monoslices_RecordsSort_InsertionSort_helper(data, a, n)
	for blockSize < n {
		a, b = 0, 2*blockSize
		for b <= n {
			monoslices_RecordsSort_SymMerge_helper(data, a, a+blockSize, b)
			a = b
			b += 2 * blockSize
		}
		if m := a + blockSize; m < n {
			monoslices_RecordsSort_SymMerge_helper(data, a, m, n)
		}
		blockSize *= 2
	}
}

func monoslices_RecordsSort_SymMerge_helper(data []Record, a, m, b int) {
	if m-a == 1 {
		i, j := m, b
		for i < j {
			h := int(uint(i+j) >> 1)
			if compareRecord(data[h], data[a]) < 0 {
				i = h + 1
			} else {
				j = h
			}
		}
		for k := a; k < i-1; k++ {
			data[k], data[k+1] = data[k+1], data[k]
		}
		return
	}
	if b-m == 1 {
		i, j := a, m
		for i < j {
			h := int(uint(i+j) >> 1)
			if !(compareRecord(data[m], data[h]) < 0) {
				i = h + 1
			} else {
				j = h
			}
		}
		for k := m; k > i; k-- {
			data[k], data[k-1] = data[k-1], data[k]
		}
		return
	}
	mid := int(uint(a+b) >> 1)
	n := mid + m
	var start, r int
	if m > mid {
		start = n - b
		r = mid
	} else {
		start = a
		r = m
	}
	p := n - 1
	for start < r {
		c := int(uint(start+r) >> 1)
		if !(compareRecord(data[p-c], data[c]) < 0) {
			start = c + 1
		} else {
			r = c
		}
	}
	end := n - start
	if start < m && m < end {
		monoslices_RecordsSort_Rotate_helper(data, start, m, end)
	}
	if a < start && start < mid {
		monoslices_RecordsSort_SymMerge_helper(data, a, start, mid)
	}
	if mid < end && end < b {
		monoslices_RecordsSort_SymMerge_helper(data, mid, end, b)
	}
}

func monoslices_RecordsSort_Rotate_helper(data []Record, a, m, b int) {
	i, j := m-a, b-m
	for i != j {
		if i > j {
			monoslices_RecordsSort_SwapRange_helper(data, m-i, m, j)
			i -= j
		} else {
			monoslices_RecordsSort_SwapRange_helper(data, m-i, m+j-i, i)
			j -= i
		}
	}
	monoslices_RecordsSort_SwapRange_helper(data, m-i, m, i)
}

func monoslices_RecordsSort_SwapRange_helper(data []Record, a, b, n int) {
	for i := 0; i < n; i++ {
		data[a+i], data[b+i] = data[b+i], data[a+i]
	}
}

type monoslices_IntsSort_SortedHint_helper int

const (
	monoslices_IntsSort_UnknownHint_helper monoslices_IntsSort_SortedHint_helper = iota
	monoslices_IntsSort_IncreasingHint_helper
	monoslices_IntsSort_DecreasingHint_helper
)

type monoslices_IntsSort_Xorshift_helper uint64

func (r *monoslices_IntsSort_Xorshift_helper) Next() uint64 {
	*r ^= *r << 13
	*r ^= *r >> 7
	*r ^= *r << 17
	return uint64(*r)
}

func monoslices_IntsSort_NextPowerOfTwo_helper(length int) uint {
	return 1 << bits.Len(uint(length))
}
